### ISSUE TITLE
Advice for install.sh

### ISSUE THREAD

**Issue by R0B3RDV** [pimoroni/hyperpixel4#141]
Hi,

Maybe its possible to check for the nessesary requirements to fully execute your script and product?
So far i was missing the following items:
sudo apt install arandr python python-dev python-rpi.gpio

that is, if you want to use Python 2.7 then... 

regards, Robert

**Comment by Gadgetoid** [comment]
Hopefully this script is now dead and buried, with the one true way being: https://github.com/pimoroni/hyperpixel4/issues/177

(users of older RPi OS versions notwithstanding)

(I think installing arandr is largely redundant since if you don't already have a desktop environment with it included, it's going to be completely ineffective)
