### ISSUE TITLE
Display gets blurry

### ISSUE THREAD

**Issue by 98Matthias** [pimoroni/hyperpixel4#66]
Hi,

If I use the display for some minutes it becomes blurry in the middle of the screen.
The picture shows the effect quite good.

I've added a 1MOhm resistor between 3v3 and INT as mentioned in a previous issue.
Otherwise the touch won't work after a while.

Is there a way to deal with this?

![IMG_20200428_191354](https://user-images.githubusercontent.com/56916751/80516987-a2e7a580-8984-11ea-9b3f-e58d34c65c87.jpg)

**Comment by Gadgetoid** [comment]
Did you mean 3v3 and *Int* or 3v3 and *Gnd* since the latter might explain what's happening here.

**Comment by Matze121** [comment]
Oh, of course 3v3 and Int is connected...

**Comment by Gadgetoid** [comment]
Is that an official power supply you're using there? It could be a power issue.

I'll ask around our engineering and testing dept to see if they've seen something like this.

**Comment by Matze121** [comment]
Thanks for your help!
I used a stable 5v/5a power supply.

**Comment by Gadgetoid** [comment]
Unfortunately nobody has seen anything like this, excepting the effect you get when hot unplugging the power while running the screen.

I still strongly suspect some sort of power supply issue, since it's the wildcard here but I don't really have anything more substantial than a hunch to back that up. If you do have another supply to try, it may be worth a go.

If all else fails, ping the support team a message at support@pimoroni.com and they will- hopefully- be able to furbish you with a replacement.

**Comment by 98Matthias** [comment]
Ok, thanks! It‘s not so bad and you can recognize everything. That‘s enough for me.
