### ISSUE TITLE
Backlight not enabled at boot

### ISSUE THREAD

**Issue by amberstarlight** [pimoroni/hyperpixel4#78]
**Describe the bug**

BCM19 is not set as an output pin which means the HyperPixel 4 does not display anything on a fresh install.

**To Reproduce**

Using a fresh image of Raspberry Pi OS (32-bit) and a new Raspberry Pi Model 4B, I used the one-line installer and selected Pi 4 and the rectangular screen option. The HyperPixel does not display anything, but this can be resolved by setting BCM19 to output. I used the following short Python script:

```py
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(19, GPIO.OUT)
```

And the screen functions as normal.

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Square
2. Touch
3. 28th May 2020
4. GPIO pins

**Your Raspberry Pi**

1. `d03114`
2. Raspbian GNU/Linux 10 (buster) `5.4.44-v7l+`
3. Fresh install

**Comment by Gadgetoid** [comment]
With my install of Raspberry Pi OS `uname -nr` outputs `raspberrypios 4.19.118-v7l+`, so I suspect this has broken since 5.x and is probably related to the `gpio=0-25=a2` line at a guess. That line was always a bit of a kludge, so it would stand to reason it would cause trouble.

Updating to see if I can replicate.
