### ISSUE TITLE
90 Degree Rotation?

### ISSUE THREAD

**Issue by drewcovi** [pimoroni/hyperpixel4#8]
Does hyperpixel4 support 90 degree touch rotation? hyperpixel 3.5 did seem to support 90 degree rotation with a small update to the python script.

**Comment by drewcovi** [comment]
note: already resolved any display issues by simply swapping width/height on framebuffers.

**Comment by drewcovi** [comment]
another note: already built from the source to enable the :rotate overlay

**Comment by Gadgetoid** [comment]
Yeah- the alternate distribution is the way to go. The source is not the same as the source used to build the upstream Linux module, but it's supplied by the manufacturer and supports a few of the chip features that are needed to handle touch/rotation properly.

I'd be interested to see if you encounter any problems with the `:rotate` parameter, as I've had at least one person say it doesn't match the screen orientation.

**Comment by dfranssen** [comment]
same issue here (using [balena docker image](https://www.balena.io/docs/reference/base-images/base-images/) `balenalib/%%BALENA_MACHINE_NAME%%-node:8` on a rpi3):

- portrait mode display (mode 4), but touch is still in landscape
- using overlay with `:rotate` is rotating the touch in landscape 180 degrees, so still no portrait mode for touch
- there seem to be some flickering, hdmi timing issues?

built from source and set following config:
- `display_rotate=4`
- `dtoverlay=hyperpixel4`
- `framebuffer_height=800`
- `framebuffer_width=480`
- `hdmi_timings=480 0 10 16 59 800 0 15 113 15 0 0 0 60 0 32000000 6`

**Comment by dfranssen** [comment]
@drewcovi did you manage to get it working? It seems really quiet here 👎

**Comment by Gadgetoid** [comment]
I'd wager the flickering issues are due to you still having something like i2c or SPI enabled, or having some process which is writing to the GPIO and interfering with the signal.

The normal touchscreen driver doesn't support portrait rotation. Are you using the alternate touchscreen driver from here? https://github.com/pimoroni/HyperPixel4TouchScreen/tree/master/driver

**Comment by dfranssen** [comment]
@Gadgetoid thanks for reaching out. 

I started with this repository and the normal goodix driver. I just tried to compile the alternate touchscreen driver you mentioned, but it was unable to build in the docker container (see details about that in my post above). I get following error and don't know if and how to resolve it. (perhaps it is related to the hostOS, which is balenaOS 2.31.5+rev1)

```
Selecting previously unselected package goodix-dkms.
(Reading database ... 64148 files and directories currently installed.)
Preparing to unpack hyperpixel4-goodix-dkms_1.0_all.deb ...
Unpacking goodix-dkms (1.0) ...
Setting up goodix-dkms (1.0) ...
Loading tarball for goodix-1.0
Loading /var/lib/dkms/goodix/1.0/4.14.52-v7+/armv7l...
DKMS: ldtarball completed.
Creating symlink /var/lib/dkms/goodix/1.0/source ->
                 /usr/src/goodix-1.0
DKMS: add completed.
It is likely that 4.15.0-45-generic belongs to a chroot's host
Building for 4.14.98+ and 4.14.98-v7+
Building for architecture armhf
Building initial module for 4.14.98+
Error! Bad return status for module build on kernel: 4.14.98+ (armhf)
Consult /var/lib/dkms/goodix/1.0/build/make.log for more information.

$ more /var/lib/dkms/goodix/1.0/build/make.log

DKMS make.log for goodix-1.0 for kernel 4.14.98+ (armhf)
Sat Apr 27 18:20:15 UTC 2019
make -C /lib/modules/`uname -r`/build KCPPFLAGS="" M=/var/lib/dkms/goodix/1.0/build modules
make[1]: *** /lib/modules/4.15.0-45-generic/build: No such file or directory.  Stop.
Makefile:13: recipe for target 'modules' failed
make: *** [modules] Error 2
```

While searching for a solution, I stumbled to this thread: https://forums.pimoroni.com/t/hyperpixel-4-touch-screen-dimensions-are-swapped/8198/29 and I recompiled the overlay with the suggested dts changes of Andy instead of the dts of this repository, as I would like to have portrait mode with the USB ports down.
This is working great and there is also no more flickering (not sure if this is related)!

**Comment by Gadgetoid** [comment]
I've now merged the changes from https://github.com/pimoroni/hyperpixel4/pull/37/files into the Raspberry Pi 3B+ support branch of HyperPixel4. This switches to using a file in `/etc/udev/rules.d/` for touchscreen calibration, in leu of dtoverlay parameters. It also includes a new `hyperpixel4-rotate` utility that sets both the touchscreen config and `display_rotate` together for 0, 90, 180 and 270 degree rotations.

Hopefully that puts this issue to bed and is a more accessible solution for the masses.
